import { Product } from './product';

export const products: Product[] = [
  {
    id: 1,
    title: "Sony WH-1000XM5",
    description: "Industry leading noise canceling with two processors controlling 8 microphones.",
    price: 15000,
    discountPercentage: 10,
    rating: 4.8,
    stock: 25,
    brand: "Sony",
    category: "headphones",
    image: "products/akhil-yerabati-Q2uV5TkjNz8-unsplash.jpg"
  },
  {
    id: 2,
    title: "Apple AirPods Max",
    description: "AirPods Max reimagine over-ear headphones. An Apple-designed dynamic driver.",
    price: 30000,
    discountPercentage: 5,
    rating: 4.7,
    stock: 15,
    brand: "Apple",
    category: "headphones",
    image: "products/c-d-x-PDX_a_82obo-unsplash.jpg"
  },
  {
    id: 3,
    title: "Bose QuietComfort 45",
    description: "The first noise cancelling headphones are back, with world-class quiet.",
    price: 12000,
    discountPercentage: 15,
    rating: 4.6,
    stock: 0,
    brand: "Bose",
    category: "headphones",
    image: "products/daniel-korpai-hbTKIbuMmBI-unsplash.jpg"
  },
  {
    id: 4,
    title: "Apple Watch Series 9",
    description: "Clearer, brighter, and more powerful. Our best selling smartwatch.",
    price: 25000,
    discountPercentage: 10,
    rating: 4.9,
    stock: 30,
    brand: "Apple",
    category: "smartwatches",
    image: "products/david-svihovec-HM-Y497t5CU-unsplash.jpg"
  },
  {
    id: 5,
    title: "Samsung Galaxy Watch 6",
    description: "The watch that knows you best is back with a more personalized health experience.",
    price: 18000,
    discountPercentage: 12,
    rating: 4.7,
    stock: 20,
    brand: "Samsung",
    category: "smartwatches",
    image: "products/ervo-rocks-Zam8TvEgN5o-unsplash.jpg"
  },
  {
    id: 6,
    title: "Sennheiser Momentum 4",
    description: "Exceptional sound quality and premium comfort for the music lover.",
    price: 14000,
    discountPercentage: 8,
    rating: 4.7,
    stock: 0,
    brand: "Sennheiser",
    category: "headphones",
    image: "products/infino-photography-LAacfd1Hn8g-unsplash.jpg"
  },
  {
    id: 7,
    title: "Garmin Fenix 7 Pro",
    description: "The ultimate multisport GPS watch with solar charging and built-in flashlight.",
    price: 35000,
    discountPercentage: 5,
    rating: 4.9,
    stock: 12,
    brand: "Garmin",
    category: "smartwatches",
    image: "products/kiran-ck-LSNJ-pltdu8-unsplash.jpg"
  },
  {
    id: 8,
    title: "Beats Studio Pro",
    description: "Fully custom acoustic platform. Personalized Spatial Audio. Active Noise Cancelling.",
    price: 11000,
    discountPercentage: 20,
    rating: 4.5,
    stock: 45,
    brand: "Beats",
    category: "headphones",
    image: "products/kiran-ck-RZmiDOpv1lM-unsplash.jpg"
  },
  {
    id: 9,
    title: "Google Pixel Watch 2",
    description: "The best of Google and Fitbit. Advanced health and fitness tracking.",
    price: 15000,
    discountPercentage: 10,
    rating: 4.6,
    stock: 0,
    brand: "Google",
    category: "smartwatches",
    image: "products/kiran-ck-UkO7K1CPFS8-unsplash.jpg"
  },
  {
    id: 10,
    title: "JBL Tour One M2",
    description: "True Adaptive Noise Cancelling technology with Smart Ambient.",
    price: 9000,
    discountPercentage: 15,
    rating: 4.4,
    stock: 60,
    brand: "JBL",
    category: "headphones",
    image: "products/klim-musalimov-IGO10LkxP_g-unsplash.jpg"
  },
  {
    id: 11,
    title: "Logitech G Pro X",
    description: "Professional-grade wireless gaming headset with Blue VO!CE technology.",
    price: 8000,
    discountPercentage: 12,
    rating: 4.8,
    stock: 18,
    brand: "Logitech",
    category: "headphones",
    image: "products/lloyd-dirks-0vsk2_9dkqo-unsplash.jpg"
  },
  {
    id: 12,
    title: "Apple Watch Ultra 2",
    description: "The most rugged and capable Apple Watch ever.",
    price: 45000,
    discountPercentage: 3,
    rating: 5.0,
    stock: 10,
    brand: "Apple",
    category: "smartwatches",
    image: "products/luke-chesser-vCF5sB7QecM-unsplash(1).jpg"
  },
  {
    id: 13,
    title: "Razer BlackShark V2",
    description: "Definitive esports gaming headset with Triforce Titanium 50mm drivers.",
    price: 5500,
    discountPercentage: 18,
    rating: 4.6,
    stock: 35,
    brand: "Razer",
    category: "headphones",
    image: "products/pratik-prasad-FPEBZJLD8Rs-unsplash.jpg"
  },
  {
    id: 14,
    title: "Huawei Watch GT 4",
    description: "Fashion Forward design with pro-level health and fitness management.",
    price: 12000,
    discountPercentage: 10,
    rating: 4.5,
    stock: 0,
    brand: "Huawei",
    category: "smartwatches",
    image: "products/sam-grozyan-yDC3NXxrtyc-unsplash.jpg"
  },
  {
    id: 15,
    title: "SteelSeries Arctis Nova",
    description: "High Fidelity drivers with 360° Spatial Audio for gaming dominance.",
    price: 13000,
    discountPercentage: 7,
    rating: 4.7,
    stock: 14,
    brand: "SteelSeries",
    category: "headphones",
    image: "products/simon-daoudi-2wFoa040m8g-unsplash(2).jpg"
  },
  {
    id: 16,
    title: "Audio-Technica M50xBT2",
    description: "The legendary M50x studio sound, now with wireless freedom and comfort.",
    price: 10000,
    discountPercentage: 5,
    rating: 4.6,
    stock: 22,
    brand: "Audio-Technica",
    category: "headphones",
    image: "products/tomasz-gawlowski-YDZPdqv3FcA-unsplash.jpg"
  }
];
